export enum DatabaseTablesEnum {
  USER_COLLECTION_NAME = 'User',
  GROUP_COLLECTION_NAME = 'Group',
  OAUTH_TOKEN_COLLECTION_NAME = 'Oauth_token',
  QUESTION_COLLECTION_NAME = 'Question',
  MODULE_COLLECTION_NAME = 'Module',
  LESSON_COLLECTION_NAME = 'Lesson',
  VISIT_LOG_COLLECTION_NAME = 'Visit_log',
  COURSE_COLLECTION_NAME = 'Course',
  COMMENT_COLLECTION_NAME = 'Comment',
  PASSED_LESSON_COLLECTION_NAME = 'Passed_lesson',
  PASSED_QUESTION_COLLECTION_NAME = 'Passed_question',
  ROOM_COLLECTION_NAME = 'Room',
  CITY_COLLECTION_NAME = 'City',
  SETTING_ROOM_COLLECTION_NAME = 'Setting_room',
  IP_COLLECTION_NAME = 'Ip'
}
